export interface GitHubCourse {
  id: string;
  title: string;
  emoji: string;
  duration: string;
  description: string;
  whatYoullLearn: string[];
  whatYoullBuild: string;
  prerequisites: string[];
  topics: string[];
  githubUrl: string;
}

export interface GitHubLevel {
  id: string;
  title: string;
  badge: string;
  color: string;
  colorRgb: string;
  bg: string;
  summary: string;
  courses: GitHubCourse[];
}

function ghUrl(repo: string) {
  return `https://github.com/new?template_owner=skills&template_name=${repo}&owner=%40me&name=skills-${repo}&visibility=public`;
}

export const GITHUB_LEVELS: GitHubLevel[] = [
  {
    id: 'foundation',
    title: 'Foundation',
    badge: '🌱',
    color: 'var(--jade)', colorRgb: '30,122,82',
    bg: 'rgba(30,122,82,0.08)',
    summary: 'Git basics, GitHub core concepts, Markdown, and publishing your first site. No prerequisites — start here.',
    courses: [
      {
        id: 'introduction-to-git',
        title: 'Introduction to Git',
        emoji: '🔀',
        duration: '< 1 hour',
        description: 'The absolute starting point. Learn how version control works using Git on the command line and in VS Code.',
        whatYoullLearn: [
          'What version control is and why it matters',
          'Core Git commands: init, add, commit, log, diff',
          'How to work with a local Git repository',
          'Navigate history and understand the commit graph',
        ],
        whatYoullBuild: 'A simple game tracked with Git — make changes and commit them step by step.',
        prerequisites: [],
        topics: ['git', 'cli', 'version-control'],
        githubUrl: ghUrl('introduction-to-git'),
      },
      {
        id: 'introduction-to-github',
        title: 'Introduction to GitHub',
        emoji: '🐙',
        duration: '< 1 hour',
        description: 'Everything you need to start contributing on GitHub: branches, commits, pull requests, and merging.',
        whatYoullLearn: [
          'Create and switch between branches',
          'Make commits and write good commit messages',
          'Open a pull request and request a review',
          'Merge a pull request into main',
        ],
        whatYoullBuild: 'A Markdown profile README — live on your GitHub profile when done.',
        prerequisites: [],
        topics: ['github', 'branches', 'pull-requests', 'commits'],
        githubUrl: ghUrl('introduction-to-github'),
      },
      {
        id: 'communicate-using-markdown',
        title: 'Communicate using Markdown',
        emoji: '📝',
        duration: '< 1 hour',
        description: 'Markdown is the language of GitHub — READMEs, issues, PRs, and wikis all use it. Master it here.',
        whatYoullLearn: [
          'Headers, emphasis, lists, and blockquotes',
          'Code blocks and syntax highlighting',
          'Tables, task lists, and emoji',
          'Linking images and files',
        ],
        whatYoullBuild: 'A formatted Markdown document covering all key syntax.',
        prerequisites: ['introduction-to-github'],
        topics: ['markdown', 'documentation'],
        githubUrl: ghUrl('communicate-using-markdown'),
      },
      {
        id: 'github-pages',
        title: 'GitHub Pages',
        emoji: '🌐',
        duration: '< 1 hour',
        description: 'Turn any GitHub repo into a free, live website in minutes — no servers, no hosting bills.',
        whatYoullLearn: [
          'Enable GitHub Pages from a repository',
          'Choose a publishing source (branch or folder)',
          'Use a Jekyll theme for instant styling',
          'Set up a custom domain (optional)',
        ],
        whatYoullBuild: 'A live personal site or project page hosted at username.github.io.',
        prerequisites: ['introduction-to-github'],
        topics: ['github-pages', 'static-sites', 'jekyll'],
        githubUrl: ghUrl('github-pages'),
      },
    ],
  },
  {
    id: 'collaboration',
    title: 'Collaboration',
    badge: '⚡',
    color: 'var(--gold)', colorRgb: '200,138,20',
    bg: 'rgba(200,138,20,0.08)',
    summary: 'The real-world skills for working in teams: reviewing code, resolving conflicts, managing history, and navigating large repos.',
    courses: [
      {
        id: 'review-pull-requests',
        title: 'Review Pull Requests',
        emoji: '👀',
        duration: '< 1 hour',
        description: 'Code review is where teams make or break quality. Learn to give useful feedback, approve changes, and request fixes.',
        whatYoullLearn: [
          'Navigate the GitHub PR diff view',
          'Add line comments and general review feedback',
          'Approve a PR or request changes',
          'Understand review states and merge conditions',
        ],
        whatYoullBuild: 'A reviewed pull request with inline comments and a final approval.',
        prerequisites: ['introduction-to-github'],
        topics: ['pull-requests', 'code-review', 'collaboration'],
        githubUrl: ghUrl('review-pull-requests'),
      },
      {
        id: 'resolve-merge-conflicts',
        title: 'Resolve Merge Conflicts',
        emoji: '⚔️',
        duration: '< 30 min',
        description: 'Merge conflicts are inevitable. Learn to read conflict markers, understand what changed, and resolve them confidently.',
        whatYoullLearn: [
          'Why merge conflicts happen',
          'Read and interpret conflict markers (<<<, ===, >>>)',
          'Resolve conflicts using the GitHub web editor',
          'Verify resolution and complete the merge',
        ],
        whatYoullBuild: 'A cleanly resolved Markdown file after intentional conflicting edits.',
        prerequisites: ['introduction-to-github'],
        topics: ['git', 'merge-conflicts', 'collaboration'],
        githubUrl: ghUrl('resolve-merge-conflicts'),
      },
      {
        id: 'connect-the-dots',
        title: 'Connect the Dots',
        emoji: '🔍',
        duration: '< 1 hour',
        description: 'Navigate large, unfamiliar repos like a senior dev — find context, trace history, and understand why things are the way they are.',
        whatYoullLearn: [
          'Use blame, search, and history to find context',
          'Trace a bug back to its introducing commit',
          'Cross-reference issues, PRs, and commits',
          'Use GitHub\'s code search effectively',
        ],
        whatYoullBuild: 'A detective-style navigation trail through a mystery repository.',
        prerequisites: ['introduction-to-github', 'review-pull-requests'],
        topics: ['github', 'navigation', 'code-search'],
        githubUrl: ghUrl('connect-the-dots'),
      },
      {
        id: 'change-commit-history',
        title: 'Change Commit History',
        emoji: '⏪',
        duration: '< 1 hour',
        description: 'Rewriting history is a power tool — learn to squash, amend, and rebase safely without breaking your team\'s workflow.',
        whatYoullLearn: [
          'Amend the most recent commit',
          'Squash commits with interactive rebase',
          'Rewrite commit messages for clarity',
          'Understand force-push risks and when it\'s safe',
        ],
        whatYoullBuild: 'A cleaned-up commit history on a feature branch.',
        prerequisites: ['introduction-to-github', 'resolve-merge-conflicts'],
        topics: ['git', 'rebase', 'commit-history'],
        githubUrl: ghUrl('change-commit-history'),
      },
      {
        id: 'introduction-to-repository-management',
        title: 'Repository Management',
        emoji: '🗂️',
        duration: '< 1 hour',
        description: 'The admin skills for a healthy repo: branch protection, issue templates, labels, and CODEOWNERS.',
        whatYoullLearn: [
          'Configure branch protection rules',
          'Create and use issue and PR templates',
          'Manage labels and milestones',
          'Set up CODEOWNERS for auto-review assignment',
        ],
        whatYoullBuild: 'A fully configured repository with templates, labels, and protection rules.',
        prerequisites: ['introduction-to-github', 'review-pull-requests'],
        topics: ['repository', 'branch-protection', 'templates'],
        githubUrl: ghUrl('introduction-to-repository-management'),
      },
    ],
  },
  {
    id: 'actions',
    title: 'GitHub Actions',
    badge: '🔧',
    color: 'var(--vermilion)', colorRgb: '192,40,28',
    bg: 'rgba(192,40,28,0.08)',
    summary: 'Automate everything — CI tests, Docker builds, releases, deployments. GitHub Actions is the most in-demand DevOps skill for AU IT roles.',
    courses: [
      {
        id: 'hello-github-actions',
        title: 'Hello GitHub Actions',
        emoji: '⚙️',
        duration: '< 30 min',
        description: 'Your first workflow file. Understand triggers, jobs, steps, and runners — the four concepts everything else builds on.',
        whatYoullLearn: [
          'YAML syntax for GitHub Actions workflows',
          'Event triggers: push, pull_request, workflow_dispatch',
          'Jobs and steps structure',
          'Using marketplace Actions',
        ],
        whatYoullBuild: 'A workflow that automatically comments on pull requests when opened.',
        prerequisites: ['introduction-to-github'],
        topics: ['github-actions', 'automation', 'yaml'],
        githubUrl: ghUrl('hello-github-actions'),
      },
      {
        id: 'test-with-actions',
        title: 'Continuous Integration',
        emoji: '🧪',
        duration: '< 1 hour',
        description: 'Every PR should run tests automatically. Learn to set up CI that catches bugs before they reach main.',
        whatYoullLearn: [
          'Build a CI workflow triggered on pull requests',
          'Run a test suite inside a workflow',
          'Read test results and failure logs',
          'Block merges when CI fails with branch protection',
        ],
        whatYoullBuild: 'A CI workflow that runs tests on every PR and reports results.',
        prerequisites: ['hello-github-actions'],
        topics: ['ci', 'testing', 'github-actions'],
        githubUrl: ghUrl('test-with-actions'),
      },
      {
        id: 'reusable-workflows',
        title: 'Reusable Workflows',
        emoji: '♻️',
        duration: '< 1 hour',
        description: 'DRY principle for CI/CD — define a workflow once, call it from multiple repos. Essential for any team at scale.',
        whatYoullLearn: [
          'Create a reusable workflow with workflow_call trigger',
          'Pass inputs and secrets to reusable workflows',
          'Call reusable workflows from other workflows',
          'Share workflows across an organisation',
        ],
        whatYoullBuild: 'A reusable deployment workflow called from two different repos.',
        prerequisites: ['hello-github-actions', 'test-with-actions'],
        topics: ['github-actions', 'reusable-workflows', 'dry'],
        githubUrl: ghUrl('reusable-workflows'),
      },
      {
        id: 'workflow-artifacts',
        title: 'Workflow Artifacts',
        emoji: '📦',
        duration: '< 1 hour',
        description: 'Pass build outputs between jobs and preserve them for download — test reports, binaries, coverage files.',
        whatYoullLearn: [
          'Upload artifacts with actions/upload-artifact',
          'Download artifacts in downstream jobs',
          'Set artifact retention periods',
          'Preview HTML reports directly from a workflow run',
        ],
        whatYoullBuild: 'A workflow that builds, uploads, and previews a test report as an artifact.',
        prerequisites: ['hello-github-actions'],
        topics: ['github-actions', 'artifacts', 'build-outputs'],
        githubUrl: ghUrl('workflow-artifacts'),
      },
      {
        id: 'release-based-workflow',
        title: 'Release-Based Workflow',
        emoji: '🚀',
        duration: '< 1 hour',
        description: 'Ship software in structured releases — tags, changelogs, GitHub Releases, and promotion between environments.',
        whatYoullLearn: [
          'Create and manage Git tags for versioning',
          'Trigger workflows on release events',
          'Generate a changelog from commit history',
          'Promote builds through staging → production',
        ],
        whatYoullBuild: 'A full release pipeline from feature branch to versioned GitHub Release.',
        prerequisites: ['hello-github-actions', 'test-with-actions'],
        topics: ['github-actions', 'releases', 'semver', 'cd'],
        githubUrl: ghUrl('release-based-workflow'),
      },
      {
        id: 'publish-docker-images',
        title: 'Publish Docker Images',
        emoji: '🐳',
        duration: '< 1 hour',
        description: 'Build and publish Docker images to GitHub Container Registry automatically on every release.',
        whatYoullLearn: [
          'Write a Dockerfile and build an image in Actions',
          'Authenticate to GitHub Container Registry (GHCR)',
          'Tag images with semver and latest',
          'Use Docker layer caching to speed up builds',
        ],
        whatYoullBuild: 'A workflow that builds a Docker image and publishes it to GHCR on every push to main.',
        prerequisites: ['hello-github-actions', 'release-based-workflow'],
        topics: ['docker', 'github-packages', 'containers', 'github-actions'],
        githubUrl: ghUrl('publish-docker-images'),
      },
    ],
  },
  {
    id: 'copilot',
    title: 'Copilot & AI',
    badge: '🤖',
    color: 'var(--jade)', colorRgb: '30,122,82',
    bg: 'rgba(30,122,82,0.08)',
    summary: '12 courses covering every Copilot feature — from first autocomplete to MCP servers, custom extensions, and AI-powered GitHub Actions.',
    courses: [
      {
        id: 'getting-started-with-github-copilot',
        title: 'Getting Started with Copilot',
        emoji: '✈️',
        duration: '< 1 hour',
        description: 'The must-do first Copilot course. Learn all four ways to interact: completions, chat, slash commands, and PR summaries.',
        whatYoullLearn: [
          'Inline completions and ghost text',
          'Copilot Chat for explaining and writing code',
          'Slash commands: /explain, /fix, /tests, /doc',
          'Copilot for PR descriptions and summaries',
        ],
        whatYoullBuild: 'A school extracurricular activities website, guided entirely by Copilot.',
        prerequisites: ['introduction-to-github'],
        topics: ['copilot', 'ai', 'vscode'],
        githubUrl: ghUrl('getting-started-with-github-copilot'),
      },
      {
        id: 'build-applications-w-copilot-agent-mode',
        title: 'Copilot Agent Mode',
        emoji: '🦾',
        duration: '< 1 hour',
        description: 'Copilot agent mode goes beyond autocomplete — it plans, creates files, runs tests, and iterates autonomously.',
        whatYoullLearn: [
          'Enable and invoke Copilot agent mode',
          'Give agent mode a multi-step task',
          'Review and approve agent-proposed changes',
          'Understand when agent mode vs chat is better',
        ],
        whatYoullBuild: 'A complete fitness tracking application built by Copilot agent mode from a single prompt.',
        prerequisites: ['getting-started-with-github-copilot'],
        topics: ['copilot', 'agent-mode', 'ai-agents'],
        githubUrl: ghUrl('build-applications-w-copilot-agent-mode'),
      },
      {
        id: 'customize-your-github-copilot-experience',
        title: 'Customise Copilot',
        emoji: '🎛️',
        duration: '< 1 hour',
        description: 'Make Copilot understand your codebase, coding style, and team conventions — custom instructions, prompt files, and chat modes.',
        whatYoullLearn: [
          'Write .github/copilot-instructions.md for repo-level context',
          'Create custom prompt files for repeated tasks',
          'Configure custom chat modes for different workflows',
          'Test and iterate on instruction quality',
        ],
        whatYoullBuild: 'A customised Copilot setup with project instructions, a refactor prompt, and a code review chat mode.',
        prerequisites: ['getting-started-with-github-copilot'],
        topics: ['copilot', 'custom-instructions', 'prompt-engineering'],
        githubUrl: ghUrl('customize-your-github-copilot-experience'),
      },
      {
        id: 'integrate-mcp-with-copilot',
        title: 'MCP with Copilot',
        emoji: '🔌',
        duration: '< 1 hour',
        description: 'Connect external tools to Copilot via MCP servers — give it access to your databases, APIs, and services.',
        whatYoullLearn: [
          'What the Model Context Protocol (MCP) is',
          'Configure a GitHub MCP server in VS Code',
          'Use MCP tools inside Copilot agent mode',
          'Build a workflow that spans Copilot + external services',
        ],
        whatYoullBuild: 'A mixed workflow using GitHub Copilot + a GitHub MCP server to manage issues and update code simultaneously.',
        prerequisites: ['getting-started-with-github-copilot', 'build-applications-w-copilot-agent-mode'],
        topics: ['copilot', 'mcp', 'agent-mode', 'integrations'],
        githubUrl: ghUrl('integrate-mcp-with-copilot'),
      },
      {
        id: 'expand-your-team-with-copilot',
        title: 'Copilot Coding Agent',
        emoji: '🤝',
        duration: '< 1 hour',
        description: 'Assign GitHub Issues directly to Copilot and let it open a PR — no local dev environment needed.',
        whatYoullLearn: [
          'Assign issues to the Copilot coding agent',
          'Review agent-opened pull requests',
          'Provide feedback in the PR to guide the agent',
          'When to use coding agent vs interactive agent mode',
        ],
        whatYoullBuild: 'A feature PR opened entirely by Copilot coding agent from an assigned issue.',
        prerequisites: ['getting-started-with-github-copilot', 'review-pull-requests'],
        topics: ['copilot', 'coding-agent', 'issues', 'automation'],
        githubUrl: ghUrl('expand-your-team-with-copilot'),
      },
      {
        id: 'copilot-code-review',
        title: 'Copilot Code Review',
        emoji: '🧐',
        duration: '< 1 hour',
        description: 'Let Copilot review your PRs automatically — catch bugs, style violations, and missing tests before human reviewers see them.',
        whatYoullLearn: [
          'Enable Copilot as a PR reviewer',
          'Interpret Copilot\'s review comments',
          'Act on suggestions with one click',
          'Configure what Copilot should focus on',
        ],
        whatYoullBuild: 'A PR with Copilot code review integrated into the branch protection workflow.',
        prerequisites: ['getting-started-with-github-copilot', 'review-pull-requests'],
        topics: ['copilot', 'code-review', 'pull-requests'],
        githubUrl: ghUrl('copilot-code-review'),
      },
      {
        id: 'create-applications-with-the-copilot-cli',
        title: 'Copilot CLI',
        emoji: '💻',
        duration: '< 1 hour',
        description: 'Use GitHub Copilot from the terminal — explain commands, suggest fixes, and build apps without leaving your shell.',
        whatYoullLearn: [
          'Install and configure GitHub Copilot in the CLI',
          'Use gh copilot suggest for command help',
          'Use gh copilot explain to understand commands',
          'Integrate Copilot CLI into a development workflow',
        ],
        whatYoullBuild: 'A Node.js calculator app, built by driving Copilot CLI through GitHub issues and commands.',
        prerequisites: ['getting-started-with-github-copilot'],
        topics: ['copilot', 'cli', 'gh-cli', 'terminal'],
        githubUrl: ghUrl('create-applications-with-the-copilot-cli'),
      },
      {
        id: 'your-first-extension-for-github-copilot',
        title: 'Build a Copilot Extension',
        emoji: '🧩',
        duration: '1–2 hours',
        description: 'Teach Copilot about your industry, internal docs, or proprietary systems by building a custom extension.',
        whatYoullLearn: [
          'What GitHub Copilot Extensions are and how they work',
          'Set up a GitHub App as an extension host',
          'Handle Copilot chat messages in your backend',
          'Stream responses back to the Copilot chat UI',
        ],
        whatYoullBuild: 'A working Copilot extension that answers questions about a custom domain.',
        prerequisites: ['getting-started-with-github-copilot', 'customize-your-github-copilot-experience'],
        topics: ['copilot', 'extensions', 'github-apps', 'api'],
        githubUrl: ghUrl('your-first-extension-for-github-copilot'),
      },
      {
        id: 'ai-in-actions',
        title: 'AI in GitHub Actions',
        emoji: '🧠',
        duration: '< 1 hour',
        description: 'Call AI models directly from your CI/CD workflows — auto-generate release notes, review diffs, or classify issues.',
        whatYoullLearn: [
          'Use GitHub Models API in a workflow step',
          'Pass context (diffs, issue text) to a model',
          'Write model output back to issues or PR comments',
          'Handle model errors and rate limits in workflows',
        ],
        whatYoullBuild: 'A workflow that uses an AI model to generate a PR summary comment automatically.',
        prerequisites: ['hello-github-actions', 'getting-started-with-github-copilot'],
        topics: ['github-actions', 'ai', 'github-models', 'automation'],
        githubUrl: ghUrl('ai-in-actions'),
      },
      {
        id: 'create-ai-powered-actions',
        title: 'Build AI-Powered Actions',
        emoji: '⚡',
        duration: '1–2 hours',
        description: 'Package AI logic into reusable GitHub Actions so any workflow in any repo can call your model with one step.',
        whatYoullLearn: [
          'Build a JavaScript Action that calls GitHub Models',
          'Accept inputs and return outputs from an AI Action',
          'Publish your Action to the marketplace',
          'Test AI Actions with mock model responses',
        ],
        whatYoullBuild: 'A published GitHub Action that uses an LLM to auto-label issues by topic.',
        prerequisites: ['hello-github-actions', 'ai-in-actions'],
        topics: ['github-actions', 'ai', 'javascript-actions', 'marketplace'],
        githubUrl: ghUrl('create-ai-powered-actions'),
      },
      {
        id: 'scale-institutional-knowledge-using-copilot-spaces',
        title: 'Copilot Spaces',
        emoji: '🌌',
        duration: '< 1 hour',
        description: 'Give your whole team access to the same curated context — docs, code, policies — through Copilot Spaces.',
        whatYoullLearn: [
          'Create and configure a Copilot Space',
          'Add repos, files, and web content as context sources',
          'Share a Space across an organisation',
          'Query institutional knowledge through Copilot chat',
        ],
        whatYoullBuild: 'A Copilot Space for a fictional company that answers questions from internal documentation.',
        prerequisites: ['getting-started-with-github-copilot', 'customize-your-github-copilot-experience'],
        topics: ['copilot', 'copilot-spaces', 'knowledge-management'],
        githubUrl: ghUrl('scale-institutional-knowledge-using-copilot-spaces'),
      },
      {
        id: 'idea-to-app-with-spark',
        title: 'Build Apps with GitHub Spark',
        emoji: '✨',
        duration: '< 1 hour',
        description: 'Describe an app in plain English and Spark builds it — no code required. Prototype ideas in minutes.',
        whatYoullLearn: [
          'Create a Spark app from a natural-language prompt',
          'Iterate on the app through conversation',
          'Add data persistence and share the app',
          'Understand when Spark vs traditional coding is appropriate',
        ],
        whatYoullBuild: 'A working web app built entirely from a description, shared via a live Spark link.',
        prerequisites: ['getting-started-with-github-copilot'],
        topics: ['spark', 'no-code', 'ai', 'prototyping'],
        githubUrl: ghUrl('idea-to-app-with-spark'),
      },
    ],
  },
  {
    id: 'security',
    title: 'Security',
    badge: '🛡️',
    color: 'var(--vermilion)', colorRgb: '192,40,28',
    bg: 'rgba(192,40,28,0.08)',
    summary: 'DevSecOps skills that employers increasingly require: supply chain security, code scanning with CodeQL, secret detection, and hands-on security challenges.',
    courses: [
      {
        id: 'secure-repository-supply-chain',
        title: 'Supply Chain Security',
        emoji: '🔒',
        duration: '< 1 hour',
        description: 'Most breaches start with a compromised dependency. Learn to understand, monitor, and secure your project\'s supply chain.',
        whatYoullLearn: [
          'Read and understand a dependency graph',
          'Enable and respond to Dependabot alerts',
          'Set up automated dependency version updates',
          'Review and pin third-party Actions to SHA',
        ],
        whatYoullBuild: 'A secured repository with Dependabot, pinned Actions, and automated update PRs.',
        prerequisites: ['introduction-to-github', 'hello-github-actions'],
        topics: ['security', 'dependabot', 'supply-chain', 'dependencies'],
        githubUrl: ghUrl('secure-repository-supply-chain'),
      },
      {
        id: 'introduction-to-secret-scanning',
        title: 'Secret Scanning',
        emoji: '🔑',
        duration: '< 1 hour',
        description: 'Prevent credentials from leaking into your codebase — GitHub will detect API keys, tokens, and passwords before they cause damage.',
        whatYoullLearn: [
          'Enable secret scanning on a repository',
          'Understand what patterns secret scanning detects',
          'Respond to a secret scanning alert',
          'Use push protection to block secrets before they\'re committed',
        ],
        whatYoullBuild: 'A repository with secret scanning + push protection enabled and a resolved alert.',
        prerequisites: ['introduction-to-github'],
        topics: ['security', 'secret-scanning', 'credentials'],
        githubUrl: ghUrl('introduction-to-secret-scanning'),
      },
      {
        id: 'introduction-to-codeql',
        title: 'Introduction to CodeQL',
        emoji: '🔬',
        duration: '< 1 hour',
        description: 'CodeQL is GitHub\'s static analysis engine — it finds security vulnerabilities in your code before attackers do.',
        whatYoullLearn: [
          'Enable code scanning with the default CodeQL setup',
          'Understand a code scanning alert and its severity',
          'Fix a vulnerability found by CodeQL',
          'Dismiss a false positive with justification',
        ],
        whatYoullBuild: 'A codebase with CodeQL scanning enabled and at least one vulnerability found and fixed.',
        prerequisites: ['secure-repository-supply-chain'],
        topics: ['codeql', 'code-scanning', 'sast', 'security'],
        githubUrl: ghUrl('introduction-to-codeql'),
      },
      {
        id: 'secure-code-game',
        title: 'Secure Code Game',
        emoji: '🎮',
        duration: '3–6 hours',
        description: 'Hands-on security training via real vulnerable code across Python, C, Go, and JavaScript — find and fix actual bugs across 3 seasons.',
        whatYoullLearn: [
          'Identify injection, path traversal, and logic bugs in real code',
          'Exploit vulnerabilities to understand them deeply',
          'Write fixes that actually close the attack surface',
          'Understand how security scanners generate their alerts',
        ],
        whatYoullBuild: 'Fixed, secure versions of 15+ intentionally vulnerable programs across 3 seasons.',
        prerequisites: ['introduction-to-codeql'],
        topics: ['security', 'vulnerability', 'python', 'go', 'javascript'],
        githubUrl: ghUrl('secure-code-game'),
      },
      {
        id: 'configure-codeql-language-matrix',
        title: 'CodeQL Language Matrix',
        emoji: '🧮',
        duration: '< 1 hour',
        description: 'Advanced CodeQL setup: scan multiple languages in parallel using build matrices to keep scan times fast at scale.',
        whatYoullLearn: [
          'Configure a CodeQL language matrix workflow',
          'Parallelise scans across languages',
          'Control scan triggers and schedule',
          'Interpret multi-language scan results',
        ],
        whatYoullBuild: 'A code scanning workflow that analyses JavaScript, Python, and Go in parallel.',
        prerequisites: ['introduction-to-codeql', 'test-with-actions'],
        topics: ['codeql', 'github-actions', 'matrices', 'advanced-security'],
        githubUrl: ghUrl('configure-codeql-language-matrix'),
      },
    ],
  },
  {
    id: 'advanced',
    title: 'Advanced DevOps',
    badge: '🏆',
    color: 'var(--gold)', colorRgb: '200,138,20',
    bg: 'rgba(200,138,20,0.08)',
    summary: 'Codespaces, cloud deployments, custom Actions, legacy modernisation, and cloud migration. Skills that command senior-level salaries.',
    courses: [
      {
        id: 'code-with-codespaces',
        title: 'Code with Codespaces',
        emoji: '☁️',
        duration: '< 1 hour',
        description: 'A full VS Code dev environment in your browser — zero setup, consistent for every team member, works on any machine.',
        whatYoullLearn: [
          'Launch a Codespace from a repository',
          'Customise the dev container with devcontainer.json',
          'Install extensions and configure the environment',
          'Commit and push changes from a Codespace',
        ],
        whatYoullBuild: 'A configured Codespace with custom extensions, settings, and a dev container spec.',
        prerequisites: ['introduction-to-github'],
        topics: ['codespaces', 'devcontainers', 'cloud-ide'],
        githubUrl: ghUrl('code-with-codespaces'),
      },
      {
        id: 'deploy-to-azure',
        title: 'Deploy to Azure',
        emoji: '☁️',
        duration: '1–2 hours',
        description: 'Automated deployments to Azure App Service and Azure Container Apps using GitHub Actions — production-grade CD.',
        whatYoullLearn: [
          'Set up Azure credentials as GitHub secrets',
          'Deploy to Azure App Service with Actions',
          'Deploy a containerised app to Azure Container Apps',
          'Configure environment-specific deployment workflows',
        ],
        whatYoullBuild: 'Two deployment workflows: one for App Service, one for containerised deployments.',
        prerequisites: ['hello-github-actions', 'publish-docker-images'],
        topics: ['azure', 'deployment', 'cd', 'cloud'],
        githubUrl: ghUrl('deploy-to-azure'),
      },
      {
        id: 'write-javascript-actions',
        title: 'Write JavaScript Actions',
        emoji: '⚙️',
        duration: '1–2 hours',
        description: 'Package any logic into a reusable, publishable GitHub Action using Node.js — build tools the whole community can use.',
        whatYoullLearn: [
          'Scaffold a JavaScript Action with action.yml',
          'Use @actions/core to read inputs and set outputs',
          'Use @actions/github to interact with the GitHub API',
          'Publish your Action to the GitHub Marketplace',
        ],
        whatYoullBuild: 'A published JavaScript Action that uses the GitHub API to automate a workflow task.',
        prerequisites: ['hello-github-actions', 'test-with-actions'],
        topics: ['github-actions', 'javascript', 'marketplace', 'node'],
        githubUrl: ghUrl('write-javascript-actions'),
      },
      {
        id: 'modernize-your-legacy-code-with-github-copilot',
        title: 'Modernise Legacy Code',
        emoji: '🏗️',
        duration: '< 1 hour',
        description: 'Use Copilot to migrate a COBOL accounting system to Node.js — the same workflow that applies to any legacy codebase.',
        whatYoullLearn: [
          'Use Copilot to explain and document unfamiliar code',
          'Generate a migration plan with Copilot Chat',
          'Translate logic from one language to another with AI',
          'Write tests for migrated code using Copilot',
        ],
        whatYoullBuild: 'A modernised Node.js version of a legacy COBOL school accounting system.',
        prerequisites: ['getting-started-with-github-copilot', 'build-applications-w-copilot-agent-mode'],
        topics: ['copilot', 'migration', 'legacy-code', 'refactoring'],
        githubUrl: ghUrl('modernize-your-legacy-code-with-github-copilot'),
      },
      {
        id: 'migrate-ado-repository',
        title: 'Migrate from Azure DevOps',
        emoji: '🚚',
        duration: '< 1 hour',
        description: 'Move repositories, history, and pipelines from Azure DevOps to GitHub using the official CLI migration tooling.',
        whatYoullLearn: [
          'Create a sample Azure DevOps project to migrate',
          'Use the gh ado2gh migrate-repo command',
          'Verify migrated history, branches, and PRs',
          'Map Azure Pipelines concepts to GitHub Actions',
        ],
        whatYoullBuild: 'A fully migrated GitHub repository with intact history from Azure DevOps.',
        prerequisites: ['introduction-to-github', 'hello-github-actions'],
        topics: ['migration', 'azure-devops', 'gh-cli', 'enterprise'],
        githubUrl: ghUrl('migrate-ado-repository'),
      },
    ],
  },
];

export const ALL_GH_COURSES = GITHUB_LEVELS.flatMap(l => l.courses);
export const TOTAL_GH_COURSES = ALL_GH_COURSES.length;
