import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import readingTime from 'reading-time';

const postsDir       = path.resolve(process.cwd(), 'content/posts');
const digestsDir     = path.resolve(process.cwd(), 'content/digests');
const githotDir      = path.resolve(process.cwd(), 'content/githot');
const aiNewsDir      = path.resolve(process.cwd(), 'content/ai-news');
const visaNewsDir    = path.resolve(process.cwd(), 'content/visa-news');
const careerEdgeDir  = path.resolve(process.cwd(), 'content/career-edge');

export interface Post {
  slug: string;
  source: 'blog' | 'digest' | 'githot' | 'ai-news' | 'visa-news' | 'career-edge';
  title: string;
  date: string;
  excerpt: string;
  tags: string[];
  readingTime: string;
  content: string;
  coverEmoji?: string;
  autoGenerated?: boolean;
  /** For ai-news posts: the publishing company */
  company?: 'anthropic' | 'openai' | 'google';
  /** For ai-news / visa-news posts: link back to the original article */
  sourceUrl?: string;
  /** For visa-news posts: affected visa subclasses */
  visaTypes?: string[];
  /** For visa-news posts: target audience groups */
  audience?: string[];
  /** For visa-news posts: the feed/source id (home-affairs, acs, etc.) */
  visaSource?: string;
  /** For career-edge posts: sub-pillar tag (ai-screening, fluency-without-debt, eval-driven-projects, pr-pathway, interview-defence, tools-deep-dive) */
  pillar?: string;
  /** For career-edge posts: Gradland tool path the article funnels readers toward (/resume, /interview-prep, /learn, /au-insights, /jobs) */
  crossLink?: string;
  /** For career-edge posts: relevant visa subclass for cross-linking (e.g. "485", "482", "186") */
  visaPathway?: string;
  /** Parsed from content: article titles (digest), repo names + stars (githot), key takeaways (ai-news), or action items (visa-news) */
  topics?: string[];
}

/** Extract up to `max` topic items from digest/githot/ai-news markdown content */
function parseTopics(content: string, source: Post['source'], max = 5): string[] {
  if (source === 'blog') return [];
  const topics: string[] = [];
  const lines = content.split('\n');

  if (source === 'digest') {
    // Lines like: ## 1. [Article Title Here](url)
    for (const line of lines) {
      const m = line.match(/^##\s+\d+\.\s+\[([^\]]+)\]/);
      if (m) {
        topics.push(m[1]);
        if (topics.length >= max) break;
      }
    }
  }

  if (source === 'githot') {
    // Lines like: ## 1. [user/repo](url)
    // Followed a few lines later by: **19,025 stars this week** · TypeScript
    for (let i = 0; i < lines.length && topics.length < max; i++) {
      const heading = lines[i].match(/^##\s+\d+\.\s+\[([^\]]+)\]/);
      if (!heading) continue;
      const repoName = heading[1].split('/').pop() ?? heading[1]; // just repo part
      // Look ahead up to 3 lines for stars
      let stars = '';
      for (let j = i + 1; j <= i + 4 && j < lines.length; j++) {
        const sm = lines[j].match(/\*\*([\d,]+)\s+stars/);
        if (sm) { stars = `⭐ ${sm[1].replace(/,(\d{3})$/, 'K').replace(/,\d{3},(\d{3})$/, 'M')}`; break; }
      }
      // Look for language
      let lang = '';
      for (let j = i + 1; j <= i + 4 && j < lines.length; j++) {
        const lm = lines[j].match(/·\s+([A-Za-z+#]+)\s*$/);
        if (lm) { lang = lm[1]; break; }
      }
      const meta = [stars, lang].filter(Boolean).join(' · ');
      topics.push(meta ? `${repoName} · ${meta}` : repoName);
    }
  }

  if (source === 'ai-news') {
    // Find "## Key takeaways" section, then extract "- ..." bullet lines
    let inSection = false;
    for (const line of lines) {
      if (/^##\s+Key takeaways/i.test(line)) { inSection = true; continue; }
      if (inSection) {
        if (line.startsWith('## ')) break; // next section
        const m = line.match(/^-\s+(.+)/);
        if (m) {
          topics.push(m[1].trim());
          if (topics.length >= max) break;
        }
      }
    }
  }

  if (source === 'visa-news') {
    // Find "## Action items" section, then extract "- [ ] ..." checkbox lines
    let inSection = false;
    for (const line of lines) {
      if (/^##\s+Action items/i.test(line)) { inSection = true; continue; }
      if (inSection) {
        if (line.startsWith('## ')) break; // next section
        const m = line.match(/^-\s+\[\s*[x ]?\s*\]\s*(.+)/i);
        if (m) {
          topics.push(m[1].trim());
          if (topics.length >= max) break;
        }
      }
    }
  }

  return topics;
}

/** Reject slugs that contain path traversal sequences or invalid characters. */
function isSafeSlug(slug: string): boolean {
  return /^[a-zA-Z0-9._-]+$/.test(slug) && !slug.includes('..') && !slug.startsWith('.');
}

/** Confirm the resolved file path stays inside the expected directory. */
function isInsideDir(dir: string, filePath: string): boolean {
  const relative = path.relative(dir, filePath);
  return !relative.startsWith('..') && !path.isAbsolute(relative);
}

function readDir(dir: string, source: Post['source'], defaultEmoji = '🤖'): Post[] {
  if (!fs.existsSync(dir)) return [];
  const files = fs.readdirSync(dir).filter(f => !f.startsWith('.') && (f.endsWith('.mdx') || f.endsWith('.md')));
  return files
    .map(file => {
      const slug = file.replace(/\.(mdx|md)$/, '');
      const raw = fs.readFileSync(path.join(dir, file), 'utf8');
      const { data, content } = matter(raw);
      return {
        slug,
        source,
        title:         data.title || 'Untitled',
        date:          data.date || new Date().toISOString(),
        excerpt:       data.excerpt || '',
        tags:          data.tags || [],
        coverEmoji:    data.coverEmoji || defaultEmoji,
        autoGenerated: data.auto_generated === true,
        company:       data.company as Post['company'] | undefined,
        sourceUrl:     data.source_url as string | undefined,
        visaTypes:     data.visa_types as string[] | undefined,
        audience:      data.audience as string[] | undefined,
        visaSource:    data.source as string | undefined,
        pillar:        data.pillar as string | undefined,
        crossLink:     data.cross_link as string | undefined,
        visaPathway:   data.visa_pathway as string | undefined,
        readingTime:   readingTime(content).text,
        content,
        topics:        parseTopics(content, source),
      };
    })
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

function getBySlug(dir: string, slug: string, source: Post['source'], defaultEmoji = '🤖'): Post | null {
  if (!isSafeSlug(slug)) return null;

  const mdxPath = path.join(dir, `${slug}.mdx`);
  const mdPath  = path.join(dir, `${slug}.md`);
  const target  = fs.existsSync(mdxPath) ? mdxPath : fs.existsSync(mdPath) ? mdPath : null;

  if (!target || !isInsideDir(dir, target)) return null;

  const raw = fs.readFileSync(target, 'utf8');
  const { data, content } = matter(raw);
  return {
    slug,
    source,
    title:         data.title || 'Untitled',
    date:          data.date || new Date().toISOString(),
    excerpt:       data.excerpt || '',
    tags:          data.tags || [],
    coverEmoji:    data.coverEmoji || defaultEmoji,
    autoGenerated: data.auto_generated === true,
    company:       data.company as Post['company'] | undefined,
    sourceUrl:     data.source_url as string | undefined,
    visaTypes:     data.visa_types as string[] | undefined,
    audience:      data.audience as string[] | undefined,
    visaSource:    data.source as string | undefined,
    readingTime:   readingTime(content).text,
    content,
    topics:        parseTopics(content, source),
  };
}

export function getAllPosts():             Post[]      { return readDir(postsDir,   'blog',   '✍️'); }
export function getPostBySlug(slug: string): Post | null { return getBySlug(postsDir,   slug, 'blog',   '✍️'); }

export function getAllDigests():               Post[]      { return readDir(digestsDir, 'digest', '🤖'); }
export function getDigestBySlug(slug: string): Post | null { return getBySlug(digestsDir, slug, 'digest', '🤖'); }

export function getAllGithot():               Post[]      { return readDir(githotDir,  'githot', '🔥'); }
export function getGithotBySlug(slug: string): Post | null { return getBySlug(githotDir,  slug, 'githot', '🔥'); }

export function getAllAINews():               Post[]      { return readDir(aiNewsDir,   'ai-news',   '📡'); }
export function getAINewsBySlug(slug: string): Post | null { return getBySlug(aiNewsDir,   slug, 'ai-news',   '📡'); }

export function getAllVisaNews():               Post[]      { return readDir(visaNewsDir, 'visa-news', '🛂'); }
export function getVisaNewsBySlug(slug: string): Post | null { return getBySlug(visaNewsDir, slug, 'visa-news', '🛂'); }

export function getAllCareerEdge():               Post[]      { return readDir(careerEdgeDir, 'career-edge', '🎯'); }
export function getCareerEdgeBySlug(slug: string): Post | null { return getBySlug(careerEdgeDir, slug, 'career-edge', '🎯'); }

export function getAllTags(): string[] {
  const tags = new Set<string>();
  getAllPosts().forEach(p => p.tags.forEach(t => tags.add(t)));
  return Array.from(tags);
}
